import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/* The admin client ships inside the Worker bundle as a string, mirroring how the OSV
   matcher wasm is generated into `src/generated`. Static assets would need an upload
   session the Terraform provider has no resource for, and a CDN would put a third-party
   origin into a security tool's `script-src`. */
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = join(root, "src/generated/admin-client.ts");

const build = await Bun.build({
  entrypoints: [join(root, "client/admin/main.tsx")],
  target: "browser",
  minify: true,
  format: "esm",
  define: { "process.env.NODE_ENV": '"production"' },
});
if (!build.success) {
  for (const log of build.logs) console.error(String(log));
  throw new Error("Admin client build failed");
}
const [artifact] = build.outputs;
if (!artifact) throw new Error("Admin client build produced no output");
const source = await artifact.text();
const digest = new Bun.CryptoHasher("sha256").update(source).digest("hex").slice(0, 16);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by scripts/build-admin.ts. Do not edit.\nexport const adminClientSource = ${JSON.stringify(source)};\nexport const adminClientDigest = ${JSON.stringify(digest)};\n`,
);
console.log(`admin client ${(source.length / 1024).toFixed(1)}KB digest ${digest}`);
